import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const firaCode = localFont({
  src: [
    {
      path: "./fonts/FiraCode/FiraCode-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/FiraCode/FiraCode-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/FiraCode/FiraCode-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/FiraCode/FiraCode-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/FiraCode/FiraCode-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-fira-code", // Define a CSS variable to use the font across your project
});

export const metadata: Metadata = {
  title: "R",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${firaCode.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
